name: flutter_template
description: Flutter App Template

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  #built_value
  built_collection: ^4.3.0
  built_value: ^7.0.0

  #core
  rxdart: ^0.23.1
  shared_preferences: ^0.5.6
  stream_disposable: ^0.0.1
  bloc_pattern:

  # Network
  dio: ^3.0.7
  http: ^0.12.0+2


dev_dependencies:
  build_runner: ^1.7.2
  built_value_generator: ^7.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true